#!/bin/bash
# ==========================================
# Backend EC2 AMI Setup Script (Amazon Linux 2023)
# ==========================================

# 1. Update OS and Install dependencies
dnf update -y
dnf install -y git curl

# 2. Install Node.js
curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
dnf install -y nodejs

# 3. Install PM2 globally to manage Node.js processes
npm install -g pm2
pm2 startup systemd
# Run the command generated by 'pm2 startup' manually if needed
env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u root --hp /root

# 4. Clone Repository (replace with your repo URL or S3 download)
# git clone https://github.com/your-org/procurement-platform.git /opt/procurement-platform
# cd /opt/procurement-platform

# Assuming files are placed in /opt/procurement-platform
cd /opt/procurement-platform

# 5. Install root dependencies and build backend workspaces
npm run bootstrap
npm run build:backend

# 6. Start the API Gateway using PM2
cd backend/gateway/api-gateway

# Set production environment variables (usually injected via Secrets Manager, but setting defaults)
export NODE_ENV=production
export PORT=5000
export AWS_REGION=us-east-1
# Note: MONGODB_URI is NO LONGER REQUIRED as we use DynamoDB via IAM Roles!

pm2 start dist/index.js --name "procurement-api-gateway"
pm2 save

echo "Backend AMI Setup Complete! DynamoDB access is handled natively via the EC2 IAM Instance Profile."
