{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: "procurement-{{ .Values.global.environment }}"
    alb.ingress.kubernetes.io/group.order: {{ .Values.ingress.groupOrder | quote }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.healthCheck.path }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    {{- if .Values.global.acmCertArn }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.global.acmCertArn | quote }}
    {{- end }}
    {{- if and .Values.global.wafAclArn (eq .Chart.Name "frontend") }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.global.wafAclArn | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.global.domain | quote }}
      http:
        paths:
          {{- range .Values.ingress.pathPrefixes }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "chart.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
{{- end }}
